In [1]:
import os
os.chdir("C:\\Users\\SHAILESH TIWARI\\Python Files\\DataSources")

In [2]:
os.getcwd()

'C:\\Users\\SHAILESH TIWARI\\Python Files\\DataSources'

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
dataset= pd.read_csv("50_Startups.csv")

In [5]:
dataset.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [6]:
x = dataset.iloc[:,0:4].values   # splitting the dataset into x

In [7]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [8]:
y = dataset.iloc[:,4].values    # splitting the dataset into y

In [9]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [10]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X=np.array(ct.fit_transform(x))
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [12]:
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [13]:
#from sklearn.preprocessing import OneHotEncoder
#onehotencoder = OneHotEncoder()
#x = onehotencoder.fit_transform(x).toarray()


In [14]:
x=X[:,1:6]

In [15]:
pd.DataFrame(x)

0  1        2        3        4
0   0  1   165349   136898   471784
1   0  0   162598   151378   443899
2   1  0   153442   101146   407935
3   0  1   144372   118672   383200
4   1  0   142107  91391.8   366168
5   0  1   131877  99814.7   362861
6   0  0   134615   147199   127717
7   1  0   130298   145530   323877
8   0  1   120543   148719   311613
9   0  0   123335   108679   304982
10  1  0   101913   110594   229161
11  0  0   100672  91790.6   249745
12  1  0  93863.8   127320   249839
13  0  0  91992.4   135495   252665
14  1  0   119943   156547   256513
15  0  1   114524   122617   261776
16  0  0  78013.1   121598   264346
17  0  1  94657.2   145078   282574
18  1  0  91749.2   114176   294920
19  0  1  86419.7   153514        0
20  0  0  76253.9   113867   298664
21  0  1  78389.5   153773   299737
22  1  0  73994.6   122783   303319
23  1  0  67532.5   105751   304769
24  0  1    77044  99281.3   140575
25  0  0  64664.7   139553   137963
26  1  0  75328.9   144136   134050
27  0  1  72107.6   127865   353184
28  1  0  66051.5   182646   118148
29  0  1  65605.5   153032   107138
30  1  0  61994.5   115641  91131.2
31  0  1  61136.4   152702  88218.2
32  0  0  63408.9   129220  46085.2
33  1  0  55493.9   103057   214635
34  0  0  46426.1   157694   210798
35  0  1    46014  85047.4   205518
36  1  0  28663.8   127056   201127
37  0  0  44069.9  51283.1   197029
38  0  1  20229.6  65947.9   185265
39  0  0  38558.5  82982.1   174999
40  0  0  28754.3   118546   172796
41  1  0  27892.9  84710.8   164471
42  0  0  23640.9  96189.6   148001
43  0  1  15505.7   127382  35534.2
44  0  0  22177.7   154806  28334.7
45  0  1  1000.23   124153  1903.93
46  1  0  1315.46   115816   297114
47  0  0        0   135427        0
48  0  1   542.05  51743.2        0
49  0  0        0   116984  45173.1

In [16]:
from sklearn.preprocessing import StandardScaler    # to make the data in  standard format to read
sc = StandardScaler()
x=sc.fit_transform(x)

In [17]:
pd.DataFrame(x)

0         1         2         3         4
0  -0.685994  1.393261  2.016411  0.560753  2.153943
1  -0.685994 -0.717741  1.955860  1.082807  1.923600
2   1.457738 -0.717741  1.754364 -0.728257  1.626528
3  -0.685994  1.393261  1.554784 -0.096365  1.422210
4   1.457738 -0.717741  1.504937 -1.079919  1.281528
5  -0.685994  1.393261  1.279800 -0.776239  1.254210
6  -0.685994 -0.717741  1.340066  0.932147 -0.688150
7   1.457738 -0.717741  1.245057  0.871980  0.932186
8  -0.685994  1.393261  1.030369  0.986952  0.830887
9  -0.685994 -0.717741  1.091819 -0.456640  0.776107
10  1.457738 -0.717741  0.620398 -0.387599  0.149807
11 -0.685994 -0.717741  0.593085 -1.065540  0.319834
12  1.457738 -0.717741  0.443260  0.215449  0.320617
13 -0.685994 -0.717741  0.402078  0.510179  0.343957
14  1.457738 -0.717741  1.017181  1.269199  0.375742
15 -0.685994  1.393261  0.897913  0.045868  0.419219
16 -0.685994 -0.717741  0.094441  0.009118  0.440446
17 -0.685994  1.393261  0.460720  0.855666  0.591017
18  1.457738 -0.717741  0.396725 -0.258465  0.692992
19 -0.685994  1.393261  0.279442  1.159837 -1.743127
20 -0.685994 -0.717741  0.055726 -0.269588  0.723926
21 -0.685994  1.393261  0.102724  1.169186  0.732788
22  1.457738 -0.717741  0.006007  0.051850  0.762376
23  1.457738 -0.717741 -0.136201 -0.562211  0.774349
24 -0.685994  1.393261  0.073115 -0.795469 -0.581939
25 -0.685994 -0.717741 -0.199312  0.656489 -0.603517
26  1.457738 -0.717741  0.035370  0.821718 -0.635835
27 -0.685994  1.393261 -0.035519  0.235069  1.174271
28  1.457738 -0.717741 -0.168793  2.210141 -0.767189
29 -0.685994  1.393261 -0.178609  1.142457 -0.858134
30  1.457738 -0.717741 -0.258074 -0.205629 -0.990357
31 -0.685994  1.393261 -0.276958  1.130554 -1.014419
32 -0.685994 -0.717741 -0.226949  0.283924 -1.362450
33  1.457738 -0.717741 -0.401129 -0.659324  0.029817
34 -0.685994 -0.717741 -0.600682  1.310535 -0.001879
35 -0.685994  1.393261 -0.609750 -1.308658 -0.045493
36  1.457738 -0.717741 -0.991570  0.205925 -0.081763
37 -0.685994 -0.717741 -0.652532 -2.525994 -0.115608
38 -0.685994  1.393261 -1.177178 -1.997270 -0.212785
39 -0.685994 -0.717741 -0.773820 -1.383122 -0.297583
40 -0.685994 -0.717741 -0.989577 -0.100900 -0.315786
41  1.457738 -0.717741 -1.008534 -1.320796 -0.384552
42 -0.685994 -0.717741 -1.102106 -0.906938 -0.520596
43 -0.685994  1.393261 -1.281134  0.217682 -1.449605
44 -0.685994 -0.717741 -1.134305  1.206419 -1.509074
45 -0.685994  1.393261 -1.600350  0.101254 -1.727400
46  1.457738 -0.717741 -1.593413 -0.199322  0.711122
47 -0.685994 -0.717741 -1.622362  0.507722 -1.743127
48 -0.685994  1.393261 -1.610433 -2.509409 -1.743127
49 -0.685994 -0.717741 -1.622362 -0.157226 -1.369985

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [19]:
from sklearn.tree import DecisionTreeRegressor
regressor =DecisionTreeRegressor()
regressor.fit(x_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [20]:
y_pred =regressor.predict(x_test)

In [21]:
y_pred

array([110352.25, 129917.04, 101004.64,  97483.56, 129917.04,  81229.06,
       122776.86,  96712.8 ,  81005.76, 166187.94])

In [22]:
y_test

array([108733.99, 152211.77,  97427.84,  99937.59, 149759.96,  71498.49,
       134307.35,  96479.51,  78239.91, 156991.12])

In [ ]:
from sklearn.metrics import mean_squared_error

rms = mean_squared_error(y_test, y_pred, squared=False)

In [ ]:
rms

In [ ]:
# concept of RMSE from regression line: RMSE = sqrt(sum(y_test-y_pred)^2/n)

In [ ]:
pd.concat([pd.DataFrame(y_test),pd.DataFrame(y_pred)],axis=1) #index joins of dataframe of actual and predicted dataset to compare

In [ ]:
from sklearn.ensemble import RandomForestRegressor  # random forest:creating multiple decision trees give better accuracy then decision tree
regressor_rf = RandomForestRegressor(n_estimators=3) #creating three samples #grid search to choose best samples
regressor_rf.fit(x_train,y_train)

In [ ]:
y_pred_rf = regressor_rf.predict(x_test)

In [ ]:
y_pred_rf

In [ ]:
pd.concat([pd.DataFrame(y_test),pd.DataFrame(y_pred), pd.DataFrame(y_pred_rf)],axis=1)

In [ ]:
from sklearn.metrics import mean_squared_error

rms = mean_squared_error(y_test, y_pred_rf, squared=False)

In [ ]:
rms