In [1]:
import os
os.chdir("C:\\Users\\SHAILESH TIWARI\\Python Files\\DataSources")

In [ ]:
# dimensionality reduction used to reduce the number of dimensions.
# check p-value first to reduce variables then after use dimensionality reduction(option)

In [2]:
os.getcwd()

'C:\\Users\\SHAILESH TIWARI\\Python Files\\DataSources'

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("Bank-data.csv")

In [5]:
df.head(10)

Index  interest_rate  credit  Gender  previous  duration Churn
0      0          1.334       0       1         0       117    no
1      1          0.767       0       0         1       274   yes
2      2          4.858       0       1         0       167    no
3      3          4.120       0       0         0       686   yes
4      4          4.856       0       1         0       159    no
5      5          0.899       0       0         0       120    no
6      6          4.962       0       0         0       337    no
7      7          4.858       0       1         0       640    no
8      8          4.962       0       0         0       663   yes
9      9          4.865       0       0         0       403    no

In [6]:
df['Churn']= df['Churn'].astype('category')
df['Churn']= df['Churn'].cat.codes        # applyied encoding on churn column

In [7]:
df

Index  interest_rate  credit  Gender  previous  duration  Churn
0        0          1.334       0       1         0       117      0
1        1          0.767       0       0         1       274      1
2        2          4.858       0       1         0       167      0
3        3          4.120       0       0         0       686      1
4        4          4.856       0       1         0       159      0
..     ...            ...     ...     ...       ...       ...    ...
513    513          1.334       0       1         0       204      0
514    514          0.861       0       0         1       806      1
515    515          0.879       0       0         0       290      0
516    516          0.877       0       0         1       473      1
517    517          4.965       0       0         0       142      0

[518 rows x 7 columns]

In [8]:
x = df.iloc[:,0:6].values

In [9]:
x

array([[  0.   ,   1.334,   0.   ,   1.   ,   0.   , 117.   ],
       [  1.   ,   0.767,   0.   ,   0.   ,   1.   , 274.   ],
       [  2.   ,   4.858,   0.   ,   1.   ,   0.   , 167.   ],
       ...,
       [515.   ,   0.879,   0.   ,   0.   ,   0.   , 290.   ],
       [516.   ,   0.877,   0.   ,   0.   ,   1.   , 473.   ],
       [517.   ,   4.965,   0.   ,   0.   ,   0.   , 142.   ]])

In [10]:
y = df.iloc[:,6].values

In [11]:
y

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [13]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

C:\Users\SHAILESH TIWARI\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
y_pred = logmodel.predict(x_test)

In [15]:
y_pred

array([0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[46, 10],
       [ 8, 40]], dtype=int64)

In [17]:
#accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8269230769230769

In [18]:
x

array([[  0.   ,   1.334,   0.   ,   1.   ,   0.   , 117.   ],
       [  1.   ,   0.767,   0.   ,   0.   ,   1.   , 274.   ],
       [  2.   ,   4.858,   0.   ,   1.   ,   0.   , 167.   ],
       ...,
       [515.   ,   0.879,   0.   ,   0.   ,   0.   , 290.   ],
       [516.   ,   0.877,   0.   ,   0.   ,   1.   , 473.   ],
       [517.   ,   4.965,   0.   ,   0.   ,   0.   , 142.   ]])

In [19]:
from sklearn.decomposition import PCA
pca = PCA(n_components=None)  # based on columns
x_train_n = pca.fit_transform(x_train)
x_test_n = pca.fit_transform(x_test)

In [20]:
pd.DataFrame(x_train)

0      1    2    3    4      5
0    513.0  1.334  0.0  1.0  0.0  204.0
1    163.0  4.966  0.0  0.0  0.0  264.0
2    511.0  4.965  0.0  0.0  0.0  479.0
3    243.0  1.281  0.0  1.0  0.0   69.0
4    219.0  4.859  0.0  1.0  0.0   51.0
..     ...    ...  ...  ...  ...    ...
409    5.0  0.899  0.0  0.0  0.0  120.0
410  203.0  1.365  0.0  0.0  0.0  815.0
411  444.0  1.039  0.0  0.0  1.0  655.0
412  316.0  4.963  0.0  0.0  0.0  988.0
413  378.0  0.714  0.0  0.0  0.0  805.0

[414 rows x 6 columns]

In [21]:
pd.DataFrame(x_train_n)

0           1         2         3         4         5
0   -178.387931 -258.232048 -1.337912  0.777997 -0.183451  0.011461
1   -132.481004   93.897091  1.933842 -0.262101 -0.018749 -0.030776
2     96.309557 -245.195379  2.344130 -0.194083 -0.051583  0.013906
3   -324.113112    6.133296 -1.704565  0.724168 -0.160534 -0.023255
4   -343.062389   29.395493  1.836359  0.745417  0.079479  0.008461
..          ...         ...       ...       ...       ...       ...
409 -282.704016  245.987303 -2.318361 -0.321423 -0.275715 -0.091367
410  419.681020   76.034829 -1.523517 -0.291370 -0.245068 -0.052855
411  269.480211 -171.191620 -1.680658 -0.358892  0.691349 -0.046064
412  597.075122  -29.928503  2.217087 -0.245429 -0.013225 -0.001762
413  416.711196  -99.226076 -1.985984 -0.259390 -0.308600 -0.038483

[414 rows x 6 columns]

In [22]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2) # define by yourself
x_train_2 = pca.fit_transform(x_train)
x_test_2 = pca.fit_transform(x_test)

In [23]:
pd.DataFrame(x_train_2)

0           1
0   -178.387931 -258.232048
1   -132.481004   93.897091
2     96.309557 -245.195379
3   -324.113112    6.133296
4   -343.062389   29.395493
..          ...         ...
409 -282.704016  245.987303
410  419.681020   76.034829
411  269.480211 -171.191620
412  597.075122  -29.928503
413  416.711196  -99.226076

[414 rows x 2 columns]

In [24]:
explained_variance = pca.explained_variance_ratio_

In [25]:
pd.DataFrame(explained_variance)

0
0  0.745514
1  0.254446

In [26]:
x_train_2

array([[-1.78387931e+02, -2.58232048e+02],
       [-1.32481004e+02,  9.38970906e+01],
       [ 9.63095568e+01, -2.45195379e+02],
       [-3.24113112e+02,  6.13329614e+00],
       [-3.43062389e+02,  2.93954927e+01],
       [ 4.23167430e+02, -2.35076392e+02],
       [-2.48210512e+02, -1.48378674e+01],
       [-2.54980685e+02,  7.89696709e+01],
       [-2.34235072e+02, -1.88413067e+02],
       [ 1.51828546e+02, -7.78092325e+00],
       [ 5.53444101e+02,  1.34453120e+02],
       [-6.79864438e+01, -6.66479864e+01],
       [ 7.03122116e+02, -1.03733708e+02],
       [ 3.69812617e+02, -3.02596218e+00],
       [ 6.15595844e+01, -1.27499439e+02],
       [-6.79021760e+01,  1.55536963e+02],
       [ 1.32305686e+02, -1.44673817e+02],
       [ 3.26474573e+00,  3.27107278e+00],
       [-3.29695312e+02,  1.70044974e+02],
       [ 1.47811177e+02,  1.17162772e+02],
       [-2.87935575e+01, -2.20199109e+02],
       [-1.88552333e+02,  6.96276458e+01],
       [-1.77984740e+01, -2.44777684e+02],
       [-7.

In [27]:
from sklearn.linear_model import LogisticRegression
logmodel_pca = LogisticRegression()
logmodel_pca.fit(x_train_2,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
y_pred_pca = logmodel_pca.predict(x_test_2)

In [29]:
y_pred_pca

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0], dtype=int8)

In [30]:
confusion_matrix(y_test,y_pred_pca)

array([[35, 21],
       [21, 27]], dtype=int64)

In [31]:
accuracy_score(y_test,y_pred_pca) #reduction in accuracy

0.5961538461538461