In [ ]:
#types of variables


In [ ]:
print("hello world")

In [ ]:
print("hello this is shailesh")

In [ ]:
customer_name ="shailesh"
customer_name

In [ ]:
type(customer_name)

In [ ]:
range = 10
type(range)

In [ ]:
sales=25.5
type(sales)

In [ ]:
sales>50


In [ ]:
type(sales)

In [ ]:
import os
os.getcwd()

In [ ]:
os.chdir("")

In [ ]:
# python collection data types
'''lists(adding ages[]to store multiple entry with different data types,with upadating a list not tuple,changing behaviour
tuples()multiple entry with different data type,fixed bahaviour,
sets:{}unique value identifier,
dictionaries: it is a key value pair{'cust_name':['a','b','c'],
'cust_age:[25,26,45]}'''
# arrays and matrix
# data frames
#use tab for automatic suggestions.

In [ ]:
list = [22,52,25,45,58,52,56,45,25]
print(list[2])

In [ ]:
list[6]

In [ ]:
list[1]=32 #updating list

In [ ]:
list[-2]

In [ ]:
list[1:4]

In [ ]:
list

In [ ]:
list[4]=25       # updating a list

In [ ]:
print(list)

In [ ]:
for i in list:
    print(i)

In [ ]:
list1=[22,25,23,24,25,28,29]

In [ ]:
list1[1:5]

In [ ]:
list1[4:-1]

In [ ]:
myfirstlist=[45,25,26,25,24,26,28,45,78]
myfirstlist[-4:-1]

In [ ]:
myfirstlist[-1:-5]

In [ ]:
languages=[['eng',['hindi'],['punjabi'],['urdu']]]

In [ ]:
languages

In [ ]:
len(languages)

In [ ]:
type(languages[0][1])

In [ ]:
mylist=[1,2,'r',True,22.5,'True']

In [ ]:
type(mylist[5])

In [ ]:
mylist.append(25) #use drop down function as required

In [ ]:
mylist

In [ ]:
mytuple=(45,42,52,25,56,25,85,95,65)

In [ ]:
mytuple[1]=25 # cant update tuple

In [ ]:
myfirsttuple = ()

In [ ]:
hours = 20 
if hours<=8:
    print("bonus 0%")
elif hours>8 and hours <=15:
    print("bonus 10%")
else:
    print("bonus 20%")

In [ ]:
# arrays for data science/loops replacement

In [ ]:
#loop: for loop
for condition:
    statement1
    statement2

In [ ]:
list(range(0,5))

In [ ]:
list(range(0,20,2))

In [ ]:
sales=[2555,4521,8524,5623,2512]
profit=(251,125,235,412,412)

In [ ]:
profitratio=[]
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

In [ ]:
import pandas as pd

In [ ]:
a=pd.dataframe(mydict)

In [ ]:
a.to_csv('a.csv')#saving file export data

In [ ]:
#creating dictionary
# and play with drop down commands

In [1]:
sales=[2555,4521,8524,5623,2512]
profit=(251,125,235,412,412)

In [2]:
profitratio=[]
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i]) #row by row execution
profitratio

[0.09823874755381605,
 0.027648750276487503,
 0.027569216330361333,
 0.07327049617641829,
 0.16401273885350318]

In [3]:
profitratio=[]  #using array below shown
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i]) #row by row execution
profitratio

[0.09823874755381605,
 0.027648750276487503,
 0.027569216330361333,
 0.07327049617641829,
 0.16401273885350318]

In [4]:
import numpy as np #for matrix multipliction using array

In [5]:
sales_array=np.array(sales)

In [6]:
sales_array

array([2555, 4521, 8524, 5623, 2512])

In [7]:
profit_array=np.array(profit)

In [8]:
profit_array

array([251, 125, 235, 412, 412])

In [9]:
profit_array/sales_array

array([0.09823875, 0.02764875, 0.02756922, 0.0732705 , 0.16401274])

In [ ]:
#generating matrix
sales_eu=[]
sales_uk=[]
sales_jp=[]

In [ ]:
sales_matrix=np.array([sales_eu,sales_jp,sales_uk])

In [ ]:
#slicing in matrix

In [ ]:
#look for github repository link by instructor